<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">removeGroupFromRole</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFNYXAgcGlwZWxpbmVNYXAgPSBuZXcgSURhdGFNYXAocGlwZWxpbmUpOw0KU3RyaW5nIGdy
b3VwTmFtZSA9IHBpcGVsaW5lTWFwLmdldEFzU3RyaW5nKCJncm91cE5hbWUiKTsNClN0cmluZyBy
b2xlTmFtZSA9IHBpcGVsaW5lTWFwLmdldEFzU3RyaW5nKCJyb2xlTmFtZSIpOw0KDQpJRGlyZWN0
b3J5U2Vzc2lvbiBzZXNzaW9uID0gQ0RTVXNlck1hbmFnZXIuZ2V0U2Vzc2lvbigpOw0KSURpcmVj
dG9yeVByaW5jaXBhbCBncm91cCA9IHNlc3Npb24ubG9va3VwUHJpbmNpcGFsQnlOYW1lKGdyb3Vw
TmFtZSwgSURpcmVjdG9yeVByaW5jaXBhbC5UWVBFX0dST1VQICk7DQpJRGlyZWN0b3J5UHJpbmNp
cGFsIHJvbGUgPSBzZXNzaW9uLmxvb2t1cFByaW5jaXBhbEJ5TmFtZShyb2xlTmFtZSwgSURpcmVj
dG9yeVByaW5jaXBhbC5UWVBFX1JPTEUgKTsNCmlmIChncm91cCA9PSBudWxsKXsNCgl0aHJvdyBu
ZXcgU2VydmljZUV4Y2VwdGlvbigiTm90IGFibGUgdG8gZmluZCBncm91cCAiICsgZ3JvdXBOYW1l
KTsNCn0NCmlmIChyb2xlID09IG51bGwpew0KCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJO
b3QgYWJsZSB0byBmaW5kIHJvbGUgIiArIHJvbGVOYW1lKTsNCn0NCnNlc3Npb24ucmVtb3ZlUHJp
bmNpcGFsRnJvbVJvbGUoZ3JvdXAuZ2V0SUQoKSwgcm9sZS5nZXRJRCgpKTs=</value>
</Values>
