<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getBelongedRolesByUser</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFNYXAgcGlwZWxpbmVNYXAgPSBuZXcgSURhdGFNYXAocGlwZWxpbmUpOw0KU3RyaW5nIHVz
ZXJuYW1lID0gcGlwZWxpbmVNYXAuZ2V0QXNTdHJpbmcoInVzZXJuYW1lIik7DQoNCklEaXJlY3Rv
cnlTZXNzaW9uIHNlc3Npb24gPSBDRFNVc2VyTWFuYWdlci5nZXRTZXNzaW9uKCk7DQpJRGlyZWN0
b3J5UHJpbmNpcGFsIHByaW5jaXBhbCA9IHNlc3Npb24ubG9va3VwUHJpbmNpcGFsQnlOYW1lKHVz
ZXJuYW1lLCBJRGlyZWN0b3J5UHJpbmNpcGFsLlRZUEVfVVNFUiApOw0KDQppZiAocHJpbmNpcGFs
ICE9IG51bGwpew0KCUxpc3Q8SURpcmVjdG9yeVJvbGU+IHJvbGVzID0gc2Vzc2lvbi5nZXRSb2xl
TWVtYmVyc2hpcChwcmluY2lwYWwuZ2V0SUQoKSk7DQoJU3RyaW5nW10gcm9sZU5hbWVzID0gbmV3
IFN0cmluZ1tyb2xlcy5zaXplKCldOw0KCWZvciAoaW50IGkgPSAwOyBpIDwgcm9sZU5hbWVzLmxl
bmd0aDsgaSsrKXsNCgkJcm9sZU5hbWVzW2ldID0gcm9sZXMuZ2V0KGkpLmdldE5hbWUoKTsNCgl9
DQoJcGlwZWxpbmVNYXAucHV0KCJyb2xlTmFtZXMiLCByb2xlTmFtZXMpOw0KfQ0KCQ==</value>
</Values>
