<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">listDirecotryServices</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURpcmVjdG9yeVNlc3Npb24gc2Vzc2lvbiA9IENEU1VzZXJNYW5hZ2VyLmdldFNlc3Npb24oKTsN
Ckxpc3Q8SURpcmVjdG9yeVNlcnZpY2U+IGRpcmVjdG9yeVNlcnZpY2VzID0gc2Vzc2lvbi5saXN0
RGlyZWN0b3J5U2VydmljZXMoKTsNCkxpc3Q8SURhdGE+IGRpcmVjdG9yeVNlcnZpY2VzRGF0YSA9
IG5ldyBBcnJheUxpc3Q8SURhdGE+KCk7DQpmb3IgKElEaXJlY3RvcnlTZXJ2aWNlIGRpcmVjdG9y
eVNlcnZpY2UgOiBkaXJlY3RvcnlTZXJ2aWNlcyl7DQoJSURhdGEgZGlyZWN0b3J5U2VydmljZURh
dGEgPSBJRGF0YUZhY3RvcnkuY3JlYXRlKCk7DQoJZGlyZWN0b3J5U2VydmljZXNEYXRhLmFkZChk
aXJlY3RvcnlTZXJ2aWNlRGF0YSk7DQoJSURhdGFNYXAgZGlyZWN0b3J5U2VydmljZURhdGFNYXAg
PSBuZXcgSURhdGFNYXAoZGlyZWN0b3J5U2VydmljZURhdGEpOw0KCWRpcmVjdG9yeVNlcnZpY2VE
YXRhTWFwLnB1dCgiaWQiLCBkaXJlY3RvcnlTZXJ2aWNlLmdldElEKCkpOw0KCWRpcmVjdG9yeVNl
cnZpY2VEYXRhTWFwLnB1dCgibmFtZSIsIGRpcmVjdG9yeVNlcnZpY2UuZ2V0TmFtZSgpKTsNCn0N
Cg0KSURhdGFNYXAgcGlwZWxpbmVNYXAgPSBuZXcgSURhdGFNYXAocGlwZWxpbmUpOw0KcGlwZWxp
bmVNYXAucHV0KCJkaXJlY3RvcnlTZXJ2aWNlcyIsIGRpcmVjdG9yeVNlcnZpY2VzRGF0YS50b0Fy
cmF5KG5ldyBJRGF0YVtkaXJlY3RvcnlTZXJ2aWNlc0RhdGEuc2l6ZSgpXSkpOw==</value>
</Values>
