<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getBelongedGroupsByGroup</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFNYXAgcGlwZWxpbmVNYXAgPSBuZXcgSURhdGFNYXAocGlwZWxpbmUpOw0KU3RyaW5nIGdy
b3VwTmFtZSA9IHBpcGVsaW5lTWFwLmdldEFzU3RyaW5nKCJncm91cE5hbWUiKTsNCg0KSURpcmVj
dG9yeVNlc3Npb24gc2Vzc2lvbiA9IENEU1VzZXJNYW5hZ2VyLmdldFNlc3Npb24oKTsNCklEaXJl
Y3RvcnlQcmluY2lwYWwgcHJpbmNpcGFsID0gc2Vzc2lvbi5sb29rdXBQcmluY2lwYWxCeU5hbWUo
Z3JvdXBOYW1lLCBJRGlyZWN0b3J5UHJpbmNpcGFsLlRZUEVfR1JPVVAgKTsNCg0KaWYgKHByaW5j
aXBhbCAhPSBudWxsKXsNCglMaXN0PElEaXJlY3RvcnlHcm91cD4gZ3JvdXBzID0gc2Vzc2lvbi5n
ZXRHcm91cE1lbWJlcnNoaXAocHJpbmNpcGFsLmdldElEKCkpOw0KCVN0cmluZ1tdIGdyb3VwTmFt
ZXMgPSBuZXcgU3RyaW5nW2dyb3Vwcy5zaXplKCldOw0KCWZvciAoaW50IGkgPSAwOyBpIDwgZ3Jv
dXBOYW1lcy5sZW5ndGg7IGkrKyl7DQoJCWdyb3VwTmFtZXNbaV0gPSBncm91cHMuZ2V0KGkpLmdl
dE5hbWUoKTsNCgl9DQoJcGlwZWxpbmVNYXAucHV0KCJncm91cE5hbWVzIiwgZ3JvdXBOYW1lcyk7
DQp9DQoJ</value>
</Values>
