<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">addRoleToRole</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFNYXAgcGlwZWxpbmVNYXAgPSBuZXcgSURhdGFNYXAocGlwZWxpbmUpOw0KU3RyaW5nIGNo
aWxkUm9sZU5hbWUgPSBwaXBlbGluZU1hcC5nZXRBc1N0cmluZygiY2hpbGRSb2xlTmFtZSIpOw0K
U3RyaW5nIHBhcmVudFJvbGVOYW1lID0gcGlwZWxpbmVNYXAuZ2V0QXNTdHJpbmcoInBhcmVudFJv
bGVOYW1lIik7DQoNCklEaXJlY3RvcnlTZXNzaW9uIHNlc3Npb24gPSBDRFNVc2VyTWFuYWdlci5n
ZXRTZXNzaW9uKCk7DQpJRGlyZWN0b3J5UHJpbmNpcGFsIGNoaWxkUm9sZSA9IHNlc3Npb24ubG9v
a3VwUHJpbmNpcGFsQnlOYW1lKGNoaWxkUm9sZU5hbWUsIElEaXJlY3RvcnlQcmluY2lwYWwuVFlQ
RV9ST0xFICk7DQpJRGlyZWN0b3J5UHJpbmNpcGFsIHBhcmVudFJvbGUgPSBzZXNzaW9uLmxvb2t1
cFByaW5jaXBhbEJ5TmFtZShwYXJlbnRSb2xlTmFtZSwgSURpcmVjdG9yeVByaW5jaXBhbC5UWVBF
X1JPTEUgKTsNCmlmIChjaGlsZFJvbGUgPT0gbnVsbCl7DQoJdGhyb3cgbmV3IFNlcnZpY2VFeGNl
cHRpb24oIk5vdCBhYmxlIHRvIGZpbmQgY2hpbGQgcm9sZSAiICsgY2hpbGRSb2xlTmFtZSk7DQp9
DQppZiAocGFyZW50Um9sZSA9PSBudWxsKXsNCgl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigi
Tm90IGFibGUgdG8gZmluZCByb2xlICIgKyBwYXJlbnRSb2xlTmFtZSk7DQp9DQpzZXNzaW9uLmFk
ZFByaW5jaXBhbFRvUm9sZShjaGlsZFJvbGUuZ2V0SUQoKSwgcGFyZW50Um9sZS5nZXRJRCgpKTs=
</value>
</Values>
