<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">searchGroups</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFNYXAgcGlwZWxpbmVNYXAgPSBuZXcgSURhdGFNYXAocGlwZWxpbmUpOw0KU3RyaW5nIHNl
YXJjaFN0cmluZyA9IHBpcGVsaW5lTWFwLmdldEFzU3RyaW5nKCJzZWFyY2hTdHJpbmciKTsNCg0K
TGlzdDxTdHJpbmc+IGdyb3VwTmFtZXMgPSBuZXcgQXJyYXlMaXN0PFN0cmluZz4oKTsNCg0KSURp
cmVjdG9yeVNlc3Npb24gc2Vzc2lvbiA9IENEU1VzZXJNYW5hZ2VyLmdldFNlc3Npb24oKTsNCmZv
ciAoSURpcmVjdG9yeVNlcnZpY2UgZGlyZWN0b3J5U2VydmljZSA6IHNlc3Npb24ubGlzdERpcmVj
dG9yeVNlcnZpY2VzKCkpew0KCUlEaXJlY3RvcnlQYWdpbmdDb29raWUgcGdDb29raWUgPSBzZXNz
aW9uLmNyZWF0ZVBhZ2luZ0Nvb2tpZShkaXJlY3RvcnlTZXJ2aWNlLmdldElEKCkpOw0KCXBnQ29v
a2llLnNldFBhZ2VTaXplKC0xKTsNCglMaXN0PElEaXJlY3RvcnlQcmluY2lwYWw+IHJlc3VsdHMg
PSBzZXNzaW9uLnNlYXJjaERpcmVjdG9yeShkaXJlY3RvcnlTZXJ2aWNlLmdldElEKCksIElEaXJl
Y3RvcnlQcmluY2lwYWwuVFlQRV9HUk9VUCwgbmV3IERpcmVjdG9yeVNlYXJjaFF1ZXJ5KHNlYXJj
aFN0cmluZywgMjAwLCBudWxsKSwgcGdDb29raWUpOw0KCWZvciAoSURpcmVjdG9yeVByaW5jaXBh
bCByZXN1bHQgOiByZXN1bHRzKXsNCgkJZ3JvdXBOYW1lcy5hZGQocmVzdWx0LmdldE5hbWUoKSk7
DQoJfQ0KfQ0KDQpwaXBlbGluZU1hcC5wdXQoImdyb3VwTmFtZXMiLCBncm91cE5hbWVzLnRvQXJy
YXkobmV3IFN0cmluZ1tncm91cE5hbWVzLnNpemUoKV0pKTs=</value>
</Values>
