<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">authenticateUser</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFNYXAgcGlwZWxpbmVNYXAgPSBuZXcgSURhdGFNYXAocGlwZWxpbmUpOw0KU3RyaW5nIHVz
ZXJuYW1lID0gcGlwZWxpbmVNYXAuZ2V0QXNTdHJpbmcoInVzZXJuYW1lIik7DQpTdHJpbmcgcGFz
c3dvcmQgPSBwaXBlbGluZU1hcC5nZXRBc1N0cmluZygicGFzc3dvcmQiKTsNCg0KSURpcmVjdG9y
eVNlc3Npb24gc2Vzc2lvbiA9IENEU1VzZXJNYW5hZ2VyLmdldFNlc3Npb24oKTsNCnRyeXsNCglJ
RGlyZWN0b3J5VXNlciB1c2VyID0gc2Vzc2lvbi5hdXRoZW50aWNhdGVVc2VyKHVzZXJuYW1lLCBw
YXNzd29yZCk7DQoJaWYgKHVzZXIgPT0gbnVsbCl7DQoJCXBpcGVsaW5lTWFwLnB1dCgiYXV0aG9y
aXplZCIsICJmYWxzZSIpOw0KCX1lbHNlew0KCQlwaXBlbGluZU1hcC5wdXQoImF1dGhvcml6ZWQi
LCAidHJ1ZSIpOw0KCQlpZiAodXNlci5nZXREaXJlY3RvcnlTZXJ2aWNlKCkgIT0gbnVsbCl7DQoJ
CQlwaXBlbGluZU1hcC5wdXQoImRpcmVjdG9yeVNlcnZpY2VOYW1lIiwgdXNlci5nZXREaXJlY3Rv
cnlTZXJ2aWNlKCkuZ2V0TmFtZSgpKTsNCgkJfQ0KCX0NCn1jYXRjaChEaXJlY3RvcnlFeGNlcHRp
b24gZSl7DQoJcGlwZWxpbmVNYXAucHV0KCJhdXRob3JpemVkIiwgImZhbHNlIik7DQp9</value>
</Values>
