<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getIdByName</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFNYXAgcGlwZWxpbmVNYXAgPSBuZXcgSURhdGFNYXAocGlwZWxpbmUpOw0KU3RyaW5nIGRp
cmVjdG9yeVNlcnZpY2VOYW1lID0gcGlwZWxpbmVNYXAuZ2V0QXNTdHJpbmcoImRpcmVjdG9yeVNl
cnZpY2VOYW1lIik7DQoNClN0cmluZyBkaXJlY3RvcnlTZXJ2aWNlSWQgPSBudWxsOw0KSURpcmVj
dG9yeVNlc3Npb24gc2Vzc2lvbiA9IENEU1VzZXJNYW5hZ2VyLmdldFNlc3Npb24oKTsNCkxpc3Q8
SURpcmVjdG9yeVNlcnZpY2U+IGRpcmVjdG9yeVNlcnZpY2VzID0gc2Vzc2lvbi5saXN0RGlyZWN0
b3J5U2VydmljZXMoKTsNCmZvciAoSURpcmVjdG9yeVNlcnZpY2UgZGlyZWN0b3J5U2VydmljZSA6
IGRpcmVjdG9yeVNlcnZpY2VzKXsNCglpZiAoZGlyZWN0b3J5U2VydmljZS5nZXROYW1lKCkuZXF1
YWxzKGRpcmVjdG9yeVNlcnZpY2VOYW1lKSl7DQoJCWRpcmVjdG9yeVNlcnZpY2VJZCA9IGRpcmVj
dG9yeVNlcnZpY2UuZ2V0SUQoKTsNCgl9DQp9DQoNCnBpcGVsaW5lTWFwLnB1dCgiZGlyZWN0b3J5
U2VydmljZUlkIiwgZGlyZWN0b3J5U2VydmljZUlkKTs=</value>
</Values>
