<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">addUserToRole</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFNYXAgcGlwZWxpbmVNYXAgPSBuZXcgSURhdGFNYXAocGlwZWxpbmUpOw0KU3RyaW5nIHVz
ZXJuYW1lID0gcGlwZWxpbmVNYXAuZ2V0QXNTdHJpbmcoInVzZXJuYW1lIik7DQpTdHJpbmcgcm9s
ZU5hbWUgPSBwaXBlbGluZU1hcC5nZXRBc1N0cmluZygicm9sZU5hbWUiKTsNCg0KSURpcmVjdG9y
eVNlc3Npb24gc2Vzc2lvbiA9IENEU1VzZXJNYW5hZ2VyLmdldFNlc3Npb24oKTsNCklEaXJlY3Rv
cnlQcmluY2lwYWwgdXNlciA9IHNlc3Npb24ubG9va3VwUHJpbmNpcGFsQnlOYW1lKHVzZXJuYW1l
LCBJRGlyZWN0b3J5UHJpbmNpcGFsLlRZUEVfVVNFUiApOw0KSURpcmVjdG9yeVByaW5jaXBhbCBy
b2xlID0gc2Vzc2lvbi5sb29rdXBQcmluY2lwYWxCeU5hbWUocm9sZU5hbWUsIElEaXJlY3RvcnlQ
cmluY2lwYWwuVFlQRV9ST0xFICk7DQppZiAodXNlciA9PSBudWxsKXsNCgl0aHJvdyBuZXcgU2Vy
dmljZUV4Y2VwdGlvbigiTm90IGFibGUgdG8gZmluZCB1c2VyICIgKyB1c2VybmFtZSk7DQp9DQpp
ZiAocm9sZSA9PSBudWxsKXsNCgl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiTm90IGFibGUg
dG8gZmluZCByb2xlICIgKyByb2xlTmFtZSk7DQp9DQpzZXNzaW9uLmFkZFByaW5jaXBhbFRvUm9s
ZSh1c2VyLmdldElEKCksIHJvbGUuZ2V0SUQoKSk7</value>
</Values>
